export const watchlistRoute = "watchlist"
export const searchRoute = "search"
export const recommendationsRoute = "recommendations"
export const trendingRoute = "trending"
export const shareRoute = "share"